[package]
name = "ceno-recursion-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-circuit = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-native-circuit = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-native-compiler = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-native-compiler-derive = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-native-recursion = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
openvm-stark-backend = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.0.0-rc.0" }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.0.0-rc.0" }
rand = { version = "0.8.5", default-features = false }
itertools = { version = "0.13.0", default-features = false }

# Plonky3
p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-util = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-monty-31 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }

# WHIR
whir = { git = "https://github.com/scroll-tech/whir.git" }
ark-ff = { version = "0.5", features = ["asm", "std"] }
ark-serialize = "0.5"