[package]
name = "ceno-recursion-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
# openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
# openvm-circuit = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1", features = ["bench-metrics"] }
# openvm-native-circuit = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
# openvm-native-compiler = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
# openvm-native-compiler-derive = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }
# openvm-native-recursion = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.0.0-rc.1" }

openvm = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier" }
openvm-circuit = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier", features = ["bench-metrics"] }
openvm-native-circuit = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier" }
openvm-native-compiler = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier" }
openvm-native-compiler-derive = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier" }
openvm-native-recursion = { git = "https://github.com/darth-cy/openvm", branch = "build/recursion-verifier" }

openvm-stark-backend = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.0.0-rc.0" }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.0.0-rc.0" }

rand = { version = "0.8.5", default-features = false }
itertools = { version = "0.13.0", default-features = false }

# Plonky3
p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-util = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-monty-31 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "b0591e9" }
p3-goldilocks = { git = "https://github.com/scroll-tech/plonky3", rev = "b0591e9" }

# WHIR
whir = { git = "https://github.com/scroll-tech/whir.git", branch = "feat/openvm-binding" }
ark-std = { version = "0.5", features = ["std"] }
ark-ff = { version = "0.5", features = ["asm", "std"] }
ark-poly = "0.5"
ark-serialize = "0.5"
nimue = { git = "https://github.com/arkworks-rs/nimue", features = ["ark"], rev="3a83250" }
nimue-pow = { git = "https://github.com/arkworks-rs/nimue", rev="3a83250" }

# Ceno
ceno_zkvm = { git = "https://github.com/darth-cy/ceno.git", branch = "feat/export_ff_ext" }
mpcs = { git = "https://github.com/darth-cy/ceno.git", branch = "feat/export_ff_ext" }
ff_ext = { git = "https://github.com/darth-cy/ceno.git", branch = "feat/export_ff_ext" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"