name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Fmt
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy -- -D warnings
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Run tests
      run: cargo test --all-features -- --nocapture
